### ISSUE TITLE
Publish-UDDashboard not available

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#146] opened 2018-05-07 14:30 UTC
The function isn't part of the commands available.

1.6.0 latest released on may 7th

**Comment by adamdriscoll** [comment] 2018-05-07 21:33
@Phyziik I'm not able to reproduce this issue. 

```
PS C:\Users\Adam> Publish-UDDashboard

cmdlet Publish-UDDashboard at command pipeline position 1
Supply values for the following parameters:
DashboardFile:
PS C:\Users\Adam> Get-Command Publish-UDDashboard

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Publish-UDDashboard                                1.6.0      UniversalDashboard

```

Do you have any other versions of UD installed?

**Comment by Phyziik** [comment] 2018-05-08 10:02
For some reason, my install-module universaldashboard -force didn't overwrite the old version.

Would it be possible to have some documentation with the publish-uddashboard?

I tried the assuming the way to use the cmdlet, and simply provided the dashboardfile path, and ran it. It gave me an error, saying that the file already exists with this name (when doing copy-item). It still created the service but it's not running and giving an error when I start it : 
![image](https://user-images.githubusercontent.com/37376232/39751140-3efff168-5285-11e8-862f-450055d2f6ad.png)
On top of that, I then tried to run the command again, but with a targetpath, and this time it failed saying that the service already exists.
Can I delete the service somehow? How do I update it, or replace it?

Thanks

**Comment by adamdriscoll** [comment] 2018-05-08 12:12
@Phyziik Try removing the service with sc:

sc.exe delete UniversalDashboard

Try running the command again with TargetPath specified. 

The idea here is that if you specify the TargetPath, it will copy the entire contents of the UD module into that location, including the dashboard.ps1. Then the service will run from there. If you don't specify that, it should copy the dashboard.ps1 to a known location and load the module from where ever you loaded it from for your PowerShell session.

**Comment by Phyziik** [comment] 2018-05-08 12:15
I played around with, and did run that sc delete UniversalDashboard. I then ran publish again with a specific target, and saw everything being copied there. Then tried to access my dashboard and I couldn't. Checked the service and it's set to automatic, but I can't Start it. It gives me the same error as posted above.

**Comment by Phyziik** [comment] 2018-05-08 13:02
Yeah, -Wait was the issue here. 

Thanks for that!

**Comment by adamdriscoll** [comment] 2018-05-08 16:49
Cool. Closing this issue and tracking the others. Both should be in the 1.6.1 release.

**Closed by adamdriscoll** 2018-05-08 16:49 UTC
