### ISSUE TITLE
UD3-Beta4 - PSUniversal- Certain actions show across multiple dashboards

### ISSUE THREAD

**Issue by dcherry88** [ironmansoftware/universal-dashboard#1648] opened 2020-06-02 21:14 UTC
#### Describe the Issue
When multiple dashboards are configured in PSUniversal, some actions will appear on the opposite dashboard page or on both dashboard pages

#### To Reproduce
Setup two dashboards. I utilized the v3 example dashboard for one.
Chips page - If you click the OnDelete chip, the info pops up on the test page of mine, not the demo page. Even if i shutdown my test page and restart the demo page, it doesn’t work on the demo page.
Modal page - when clicking on the examples to display modal popups, they show properly on the Modal page, but they also show on the page of my test dashboard.

#### Expected behavior
Action should only occur on the dashboard it is scripted into.

#### Version Information
Server 2019, IIS
PSUniversal 1.1.1
Utilizing UD 3.0.0-beta4, running process as powershell.exe on both dashboards.

**Comment by adamdriscoll** [comment] 2020-06-02 21:17
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/certain-actions-show-across-multiple-dashboards/2875/3

**Comment by dcherry88** [comment] 2020-06-02 21:30
> This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:
> 
> https://forums.universaldashboard.io/t/certain-actions-show-across-multiple-dashboards/2875/3

I linked it on that thread, you've created a feedback loop!

**Comment by dcherry88** [comment] 2020-06-03 19:21
Followup on this, I feel like the issue is the same underlying problem:

When clicking a page link on the side navigation of the demo site, i'm noticing that it's also trying to load that page on the tab for my test site.

Example: If I go to the appbar page on my demo site, URL is this 'portal.domain.com/demo/appbar'
If I then go to the tab where my test site is, at the root 'portal.domain.com/' it will now be on a Page Not Found with the url as 'portal.domain.com/appbar'

**Comment by AlonGvili** [comment] 2020-06-04 06:34
i can confirm , this bug also effects antd lib
[video of the bug](https://drive.google.com/file/d/1ugU1qy2cRP5viZLGqVL6UiqMdLnY_eF6/view?usp=sharing)

**Comment by adamdriscoll** [comment] 2020-06-04 17:52
Looking into this today

**Comment by adamdriscoll** [comment] 2020-06-04 18:19
This has been resolved in PSU1.2. The problem was that the websocket was broadcasting to all connected clients rather than a specific client.

**Closed by adamdriscoll** 2020-06-04 18:19 UTC
Labels: bug
