### ISSUE TITLE
PSFramework module breaks endpoints

### ISSUE THREAD

**Issue by gerane** [ironmansoftware/universal-dashboard#1197] opened 2019-09-29 16:52 UTC
#### Describe the Issue
This only seems to happen about 80-90% of the time, and doesn't seem to happen on all types of endpoints. I'm only really seeing this inside of udtable and udgrid. Even if used as content this can break. When the PSFramework module is loaded, only a small number of the functions get loaded, and the same happens to other built in modules. The grids and tables will error and display errors that X command is not a known command. 

If I check the loaded modules, I'll see that only a couple commands of the 88 commands get loaded. Other commands like set-location might error as well.

I will update this issue later with exact examples, but more or less I'm using import-psconfig, then get-psconfigvalue, which is then piped to export udgrid or udtable data. I've tried adding direct module imports to he endpoints but same results.

#### To Reproduce
Will update this later. I'm only seeing this in my dev environment, and not in prod. This mainly is just making dev much more difficult.

#### Expected behavior
Modules load as expected.

#### Screenshots
Will add these later when I'm at my PC. Adam also has some screenshots of this.

#### Script Sample
Will add these later when I'm at my PC.

#### Version Information
- **Operating System**: dev: windows 10, prod: server 2016
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.6.0, need to test on 2.6.2
- **UD Hosting Method**: dev: Powershell, prod: IIS

**Comment by awickham10** [comment] 2019-10-01 21:04
That's interesting. I'm using PSFramework on one of my dashboards and don't have any issue. I have API endpoints and pages that both uses Write-PSFMessage, Stop-PSFFunction, and Get-PSFConfigValue. I'm getting it into the endpoints by using New-UDEndpointInitialization. I'm also on 2.6.0.

**Comment by adamdriscoll** [comment] 2019-10-19 19:00
Since we can't reproduce, closing. Please reopen if you have a good way to reproduce this.

**Closed** 2019-10-19 19:00 UTC
Labels: bug
