### ISSUE TITLE
Start-UDDashboard crashes snap-pwsh

### ISSUE THREAD

**Issue by khaffner** [ironmansoftware/universal-dashboard#870] opened 2019-06-09 17:39 UTC
Works well with pwsh 6.2.1 on my raspberry pi, but crashes on my laptop with Ubuntu 19.04 and pwsh  6.2.1 installed as a snap package. Tried reinstalling pwsh. Not sure what more I can test. Steps to reproduce:
- Install Ubuntu 19.04
- sudo snap install powershell
- Install-Module UniversalDashboard.Community -Force -AcceptLicense
- Follow the [Getting Started](https://docs.universaldashboard.io/getting-started) guide, Start-UDDashboard should terminate the powershell session.

**Comment by TylerLeonhardt** [comment] 2019-12-04 19:57
@TravisEz13 any ideas on how they can debug this?

**Comment by TravisEz13** [comment] 2019-12-04 21:24
try this with the powershell-preview snap

**Comment by the-mentor** [comment] 2019-12-05 22:16
Hi @TravisEz13 I tried it with the powershell-preview snap and the same thing happen.
The process segment faults and drops me back into bash.

-DM

**Comment by TravisEz13** [comment] 2019-12-06 19:42
does UDDashboard have its own native requirements?

**Comment by adamdriscoll** [comment] 2019-12-07 04:47
@TravisEz13 The 2.7 (current release) is using libuv which is a native library used by older versions of ASP.NET Core. 2.8 will be removing this dependency and will start using .NET Core sockets instead.

**Comment by TravisEz13** [comment] 2019-12-07 22:20
@adamdriscoll The problem probably cannot be resolved in snap until this is resolved.

DotNet's loading of native libraries is fragile.  Certain libraries must be matched and if we investigate, the problem is probably due to this libraries decencies causing a two libraries to load which don't work together and thus segfault.  

cc @stevel-msft

**Closed** 2019-12-09 20:47 UTC
Labels: bug, needs validation
