### ISSUE TITLE
Commands in Buttons

### ISSUE THREAD

**Issue by jello3d** [ironmansoftware/universal-dashboard#239] opened 2018-06-26 03:08 UTC
I am trying to do something like this:

New-UDButton -Text 'PatchTest' -OnClick { Get-WUInstall -ComputerName $Computer -Install -Acceptall -Autoreboot -Verbose }

I can use an Invoke-command and make it work... but nothing happens when running it directly.  Tried adding ipmo pswindowsupdate; no go.  All the native commands I've tried seem to work as an onClick.

Any thoughts? 

----- Update

Also, while I can make the Invoke-Command work as part of a standalone button or as part of a UDTable, I cannot make it work as part of a UDGrid.  The button shows up, but I can't get it to execute the command.  With UDTable the button shows and executes normally.

----- Update 2

Last edit - if a variable is part of the command, it will not work in either case -

So:
 
Patch=(New-UDButton -Text 'Patch' -OnClick { Invoke-Command -ComputerName 'NAME' -ScriptBlock { ipmo pswindowsupdate; Get-WUInstall -Install -Acceptall -Autoreboot -Verbose }})

...will work with UDTable, not UDGrid

Patch=(New-UDButton -Text 'Patch' -OnClick { Invoke-Command -ComputerName $Name -ScriptBlock { ipmo pswindowsupdate; Get-WUInstall -Install -Acceptall -Autoreboot -Verbose }})

...will *not* work with either UDTable or UDGrid.

Note that I am trying to display a list of machines, whether they need patches, and a button that will execute a command to patch them.  While I can make it work for individuals... I can't yet seem to make it work in a table or grid... with varying degrees of failure.

Thanks

**Comment by adamdriscoll** [comment] 2018-07-01 13:47
Can you please get a log of the failures? Enable-UDLogging should do it.

**Comment by jello3d** [comment] 2018-07-02 04:58
Basically variables are not being enumerated within the -onclick {}

For example, if I only have this on a page:

    $name='computer'
    New-UDButton -Text 'Patch' -OnClick { Invoke-command -ComputerName $name -ScriptBlock { Get-WUInstall -Install -Acceptall -Autoreboot -Verbose }}
 
The logs show:

00:53:08 ExecutionService OnClick =  Invoke-command -ComputerName $name -ScriptBlock { Get-WUInstall -Install -Acceptall -Autoreboot -Verbose }

and the error is

00:53:08 ExecutionService Error executing endpoint script. One or more computer names are not valid. If you are trying to pass a URI, use the -ConnectionUri parameter, or pass URI objects instead of strings.

which is the error you would expect.


do you have to escape the variables somehow, or is this just a bug?

thx

**Comment by jello3d** [comment] 2018-07-06 23:19
I know you have a lot to fix/add... but do you have a vague eta on 1.7... or perhaps a 1.6.x that handles a few of the low hanging fruit?

**Comment by adamdriscoll** [comment] 2018-07-08 16:46
@jello3d I can reproduce this issue. Still not exactly sure what is going on. You can work around this by using the session provider: 

```
$Session:name='computer'
New-UDButton -Text 'Patch' -OnClick { Invoke-command -ComputerName $Session:name -ScriptBlock { Get-WUInstall -Install -Acceptall -Autoreboot -Verbose }}
```

This seems to work in my tests. 

The issue here is that when you call New-UDButton, internally, the New-UDElement cmdlet is calling Get-Variable to return all the variables that are available in the scope so it can provide the values to the runspace that will be running the endpoint. The issue is the Get-Variable doesn't return the variable you're after. Through all scopes (0-n), Script and Local, the variable doesn't show up. 

I think I will have to revisit how variables are being passed through to endpoints. It works inconsistently.

For example, this will work;

```
 1..5 | ForEach-Object {
                New-UDElement -Tag "div" -Id "element$_" -Endpoint {
                    $_
                }
            }
``` 

The endpoint parameter is also a script block and is making the same Get-Variable call to locate variables in it's scope. 

All that said, this isn't low hanging fruit for the reasons I mention above. I've been chasing this issue every release and it seems to transform a bit. It's closer but still not quite resolved. 

For now, I suggest using the Session scope to work around this. You can also use Global scope which seems to alleviate the issue as well. 

In the next major release, I may change this to require a -Arguments parameter (like Start-Job) to pass in variables you desire to have in the scope of an endpoint.

**Comment by adamdriscoll** [comment] 2018-08-18 03:02
This has been resolved in 2.0. Event handlers can now use New-UDEndpoint and pass in an argument list. For example: 

$Name='computer'
New-UDButton -Text 'Patch' -OnClick (New-UDEndpoint -Endpoint { Invoke-command -ComputerName $ArgumentList[0] -ScriptBlock { Get-WUInstall -Install -Acceptall -Autoreboot -Verbose }} -ArgumentList $Name)

**Closed by adamdriscoll** 2018-08-18 03:02 UTC
Labels: bug

**Comment by jello3d** [comment] 2018-08-18 03:57
Noice.  Is there a new beta inbound?

**Comment by adamdriscoll** [comment] 2018-08-18 04:05
@jello3d I'll try beta3 out in a couple days. Few more issues on my hit list.

**Comment by jello3d** [comment] 2018-09-07 20:05
I'm still confused on how this is supposed to work... -argumentlist doesn't seem to be available in 2.0.1.  I may not be understanding how enpoints work.  In the example below, everything works as expected, except that the button doesn't execute anything.

`
ipmo pssqlite
ipmo pswindowsupdate
$Patches = Invoke-SqliteQuery -DataSource "C:\Data\posh.db" -Query "SELECT Name,Critical,Important,Total,Patch FROM UPDATES ORDER BY NAME"




$Page1 = New-UDPage -Name "Home" -Icon home -Content {
    
    $List = @(
        foreach ($Patch in $Patches) {
        
                       
            [PSCustomObject]@{Name=$Patch.Name;Critical=$Patch.critical;Total=$Patch.total;Patch=(New-UDButton -Text $Patch.Name -OnClick {New-UDEndpoint -Endpoint { Get-WUInstall -ComputerName $Patch.name -Install -Acceptall -Autoreboot -Verbose }}  )}
        }
    )
    
    
    New-UDGrid -RefreshInterval 1000 -Title "Process Information" -NoPaging -Headers @("Name", "Critical", "Total", "Patch") -Properties @("Name", "Critical", "Total", "Patch")  -Endpoint {
         $List | Out-UDGridData
    }

}



$FormLogin = New-UDAuthenticationMethod -Endpoint {
    param([PSCredential]$Credentials)
	Import-Module ADAuth
	$AuthorizedGroup = 'Domain Admins'
    if ($Credentials | ? {$_ | Test-ADCredential} | Test-ADGroupMembership -TargetGroup $AuthorizedGroup) {
        New-UDAuthenticationResult -Success -UserName $Credentials.UserName
    }
    New-UDAuthenticationResult -ErrorMessage "Login/Password combination incorrect"
}

$LoginPage = New-UDLoginPage -AuthenticationMethod @($FormLogin)

$Dashboard = New-UDDashboard -LoginPage $LoginPage -Page @(
    $Page1
    ) -Title "TestStuff" 

Get-UDDashboard | Stop-UDDashboard

$cert = ( Get-ChildItem -Path cert:\LocalMachine\WebHosting\**** )
Start-UDDashboard -port 1006 -Dashboard $Dashboard -Certificate $cert
`

**Comment by adamdriscoll** [comment] 2018-09-07 20:46
New-UDEndpoint definitely has a ArgumentList in 2.0.1. Make sure you don't have more than one version of the module installed. 

https://github.com/ironmansoftware/universal-dashboard/blob/master/src/UniversalDashboard/Cmdlets/NewEndpointCommand.cs#L15

Try changing your code like this: 

```powershell
        [PSCustomObject]@{Name=$Patch.Name;Critical=$Patch.critical;Total=$Patch.total;Patch=(New-UDButton -Text $Patch.Name -OnClick (New-UDEndpoint -Endpoint { Get-WUInstall -ComputerName $ArgumenstList[0].name -Install -Acceptall -Autoreboot -Verbose } -ArgumentList $Patch )  )}
```

Notice that I cahnaged the OnClick handler to use a parenthesis rather than a squiggly brace and added the argumentList parameter.

**Comment by jello3d** [comment] 2018-09-07 21:14
Ah, I see the syntax now... but it's still not doing anything.  I also tried this -

'[PSCustomObject]@{Name=$Patch.Name;Critical=$Patch.critical;Total=$Patch.total;Patch=(New-UDButton -Text $Patch.Name -OnClick (New-UDEndpoint -Endpoint { Invoke-Command -ComputerName $ArgumentList[0].Name -scriptblock { Get-wuinstall -Acceptall -Autoreboot -Verbose }} -ArgumentList $Patch ))}`

**Comment by adamdriscoll** [comment] 2018-09-07 21:41
@jello3d I would try two things. First, use Enable-UDLogging to see if there are any errors popping up when you try and clicked the button.

Second, try using Wait-Debugger within the New-UDEndpoint to see if you can debug within the endpoint to see if the variable is being set or not. I have a walk through on how to do that here: https://docs.universaldashboard.io/debugging

**Comment by jello3d** [comment] 2018-09-08 03:09
I do get the following from udlogging when I click a button:

23:05:48 Quartz.Core.QuartzSchedulerThread Batch acquisition of 0 triggers
23:05:48 ExecutionService ExecutionService constructor
23:05:48 DashboardHub ClientEvent 884bc1fe-d5f4-419e-8c83-b70472770bd2 onClick
23:05:48 EndpointService Get() 884bc1fe-d5f4-419e-8c83-b70472770bd2
23:05:48 DashboardHub Endpoint 884bc1fe-d5f4-419e-8c83-b70472770bd2 not found.
23:05:48 DashboardHub Failed to execute endpoint. Endpoint 884bc1fe-d5f4-419e-8c83-b70472770bd2 not found.

**Comment by jello3d** [comment] 2018-09-10 15:55
I dunno, I just can't make it work... even when you strip away the grid and the foreach{} I the endpoint still won't stay.  It's like it gets created and immediately deleted.
