### ISSUE TITLE
Update Web.Config in 2.0.0 for net471

### ISSUE THREAD

**Issue by mylabonline** [ironmansoftware/universal-dashboard#341] opened 2018-09-02 12:21 UTC
I had uploaded the 2.0.0 module to a test web app I have running in Azure and the dashboard did not load. I got a 502.5 Process Failure error page.

After looking into the log found error - failed to start process with commandline 'D:\home\site\wwwroot\net462\universaldashboard.server.exe '

I updated the web.config with <aspNetCore processPath=".\net471\universaldashboard.server.exe" and the page loaded as expected.

**Comment by adamdriscoll** [comment] 2018-09-02 15:11
Duplicate of #328. This has already been resolved and will be in a version releasing the next couple days.

**Closed by adamdriscoll** 2018-09-02 15:11 UTC
