### ISSUE TITLE
2.4-beta1: code_fork icon throws an error

### ISSUE THREAD

**Issue by BlueArcherX** [ironmansoftware/universal-dashboard#768] opened 2019-05-04 03:06 UTC
Using: New-UDLink -Text "foo" -Url "https://foo.bar" -Icon 'code_fork'

New-UDLink : Cannot bind parameter 'Icon'. Cannot convert value "code_fork" to type "UniversalDashboard.Models.FontAwesomeIcons". Error: "Unable to match the identifier name code_fork to a valid enumerator name. Specify one of the following enumerator names and try again.  

This was working in 2.3, and from looking through the list of options, it appears maybe this is referred to as code_branch in 2.4 instead, which may be causing the problem.

It is titled code-fork on FA4.7 as well, and there is no icon named code-branch.

**Comment by adamdriscoll** [comment] 2019-05-04 04:23
I need to fix this. The problem is that we moved to the new FA 5 library but there are a lot of icons that changed class names. I might roll back the change for now until I come up with a better solution.

**Comment by BlueArcherX** [comment] 2019-05-04 04:58
I see.  The only reason I mentioned FA4.7 was because the .js file that is loaded on my dashboard in 2.4 still shows FA4.7.  I poked around the other .js files to make sure I wans't missing something, but did not see any FA5 things.  But feel free to smack me in the head if I am being blind!

D:\<user>\Documents\PowerShell\Modules\UniversalDashboard.Community\2.4.0\client\vendors~font-awesome.1861f16e5bc27dc9f74f.bundle.js

contains: 
// module
exports.push([module.i, "/*!\n *  Font Awesome 4.7.0 by @davegandy - http://fontawesome.io - @fontawesome\n *

**Comment by adamdriscoll** [comment] 2019-05-04 13:23
It looks like we had both packages included in this beta1 release. Double-ugh. Explains why the package size is larger. ;)

**Comment by adamdriscoll** [comment] 2019-05-08 10:30
Just merged a PR that supports backwards compat for 4.7 icon names and maps them to the 5.0 FA icon equivalents. I also completely removed the 4.7 package.

**Closed by adamdriscoll** 2019-05-08 10:30 UTC
Labels: bug
