### ISSUE TITLE
New-UDInput(Field) variable behavure

### ISSUE THREAD

**Issue by ServerCare** [ironmansoftware/universal-dashboard#59] opened 2018-03-27 08:29 UTC
When using for example a checkbox: 
New-UDInputField -Type 'checkbox' -Name 'var' -Placeholder 'test' -DefaultValue $false

I would expect the default value to be represented in the checkbox state on the page (true = checked, false = not checked)

Additionally: not selecting a value (either checking or unchecking) but still selectinmg 'submit' results in the last value of the param to be given back, rather than the state of the checkbox.

Test it: https://www.poshud.com/Inputs#!
check the checkbox one, and receive a 'checked'. After submitting the state of the checkbox is cleared (why?) but when re-submitting (without checking or unchecking the checkbox) we still get to see a 'checked'.

**Comment by apetitjean** [comment] 2018-04-01 17:42
I was about to open the same issue. Thanks!

**Comment by apetitjean** [comment] 2018-04-01 17:52
In addition to this issue, when I submit my form all the fields are reset which is an expected behavior (because I used the -ClearInput parameter of New-UDInputAction). My issue here is the reset form that the default values of my controls (checkbox, listbox) are not kept.

**Comment by adamdriscoll** [comment] 2019-06-04 13:44
This has been resolved in the 2.4 build.

**Closed by adamdriscoll** 2019-06-04 13:44 UTC
Labels: bug
