### ISSUE TITLE
Modify New-UDGrid -DefaultSortColumn sort method

### ISSUE THREAD

**Issue by JLogan3o13** [ironmansoftware/universal-dashboard#1499] opened 2020-02-04 15:28 UTC
#### Is your Enhancement request related to a problem? Please describe
When creating a grid and using -DefaultSortColumn, the sort method seems to get hung up on case sensitivity. 

Sample CSV style:
   Server | CPU | RAM | Decom Date
     xxx        2         4        01/01/20

`$aDecoms = Import-Csv -Path <Path to CSV> -UseCulture`

`$myDash = New-UDDashboard -Title "Decommissions" -Content {
    New-UdGrid -Title "Decommissioned Servers"  -DefaultSortColumn "Server" -Endpoint {
        $aDecoms |
                Out-UDGridData -TotalItems $aDecoms.Count
    }
}`

`Start-UDDashboard -Dashboard $myDash -Port 666`

In this example, server "CMOMSADFSWV0002" will be on Page 1 of the output, while "cmomsadfswv0002" would be on page 8.

#### Describe the solution you'd like
It would be great to modify the sort function to ignore case, or add a parameter if there is a situation where case sensitivity would be needed (I could not think of one off the top of my head, but could be wrong).

#### Describe how this would improve your Universal Dashboard Quality of Life
This would increase the reliability of the sort function when pulling data from an external source (CSV, database, etc.) into a grid.

#### Describe alternatives you've considered
The methodology for the sort just needs to be changed; I am guessing it is a regex, as PS Sort-Object would by default be case insensitive. In fact, by removing the -DefaultSortColumn parameter and changing the Out-UDGridData line to this:

'$aDecoms |
    Out-UDGridData -TotalItems $aDecoms.Count'

it is sorted correctly. So this is definitely a workaround, but it would be a nice enhancement to have this done natively.

#### Additional context
Please :)

**Comment by augiaugi** [comment] 2020-02-04 19:38
Relate issue: https://github.com/ironmansoftware/universal-dashboard/issues/1048

**Comment by augiaugi** [comment] 2020-02-04 19:39
Related issue: https://github.com/ironmansoftware/universal-dashboard/issues/471

**Comment by adamdriscoll** [comment] 2020-02-04 21:02
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/case-sensitive-udgrid-sorting/2152/1

**Comment by adamdriscoll** [comment] 2020-02-04 22:34
Duplicate of #471 - We will use that to track. Targeting a fix for 2.9.

**Closed by adamdriscoll** 2020-02-04 22:34 UTC
Labels: enhancement
