### ISSUE TITLE
New-Guid is not recognized...when launching dashboard via IIS with v1.6.1

### ISSUE THREAD

**Issue by RCDS1** [ironmansoftware/universal-dashboard#157] opened 2018-05-09 19:24 UTC
Using default poshud and pages encounter the attached error.

Any page via the hamburger menu works fine.

![new-guid](https://user-images.githubusercontent.com/39102853/39835029-5b2fabc8-53be-11e8-8339-db86ac32ea4c.jpg)

**Comment by apetitjean** [comment] 2018-05-09 19:31
`New-Guid` is a relatively new PowerShell command. Which version do you use?

If I remember well this cmdlet was introduce with PowerShell 5.0. I would recommend you to use at least PowerShell 5.1 or PowerShell Core 6.0.

**Comment by RCDS1** [comment] 2018-05-09 19:52
I didn't have this issue with v 1.5.3

**Comment by adamdriscoll** [comment] 2018-05-09 20:39
The problem is that all the UDControls use New-Guid to create IDs. 

https://github.com/ironmansoftware/ud-controls/blob/master/src/button.ps1#L4

Will have to fix for 5.0 support.

**Comment by RCDS1** [comment] 2018-05-09 20:58
With PSVersion 5.0.10586.117 I do have New-Guid

![new-guid-ishere](https://user-images.githubusercontent.com/39102853/39839433-9c50c2ce-53cb-11e8-85a7-4f8214b9dcc0.jpg)

**Comment by adamdriscoll** [comment] 2018-05-09 22:04
Whoa. That's very weird. I'll try and get a 5.0 box stood up to see if I can reproduce this.

**Comment by petercovach** [comment] 2018-06-26 17:17
I can also confirm that is is broken on 5.0 and is fixed when the server is updated to 5.1.

**Comment by adamdriscoll** [comment] 2018-11-30 14:31
Closing as the requirements for UD are now 5.1+.

**Closed by adamdriscoll** 2018-11-30 14:31 UTC
Labels: bug
