### ISSUE TITLE
Forms layout: provide more control / guidance

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#420] opened 2018-10-29 09:22 UTC
How to arrange the positioning of the input elements? Currently it seems there is no way to organize the input fields on the screen, or a least I don't know how to do it.

Let say for example I have a form with these 3 fields:
   - Surname
   - Name
   - Email

How can I place the fields side-by-side horizontally (I mean on the same line)? By default they are displayed vertically (the input fields are stacked).

**Comment by adamdriscoll** [comment] 2019-08-07 19:06
Duplicate of #744

**Closed by adamdriscoll** 2019-08-07 19:06 UTC
Labels: enhancement, help wanted
