### ISSUE TITLE
UDInput default value not showing up

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#1248] opened 2019-10-11 17:37 UTC
<eom>

**Comment by mattselle** [comment] 2019-12-18 03:29
Hi, @mkellerman could you provide a sample for this issue? I currently am not able to reproduce this.

**Comment by adamdriscoll** [comment] 2020-03-03 22:29
Fixed in the current v3 build with UDForm.

**Closed by adamdriscoll** 2020-03-03 22:29 UTC
Labels: bug
