### ISSUE TITLE
Get-UDElement broken in 2.0.0?

### ISSUE THREAD

**Issue by pldmgg** [ironmansoftware/universal-dashboard#336] opened 2018-09-01 18:19 UTC
To recreate this issue, try the following:

```powershell
Set-Content -Path "$HOME\Test-UD.ps1" -Value @'
function Test-UD {
    Param (
        [Parameter(Mandatory=$False)]
        [switch]$RemoveAllOtherUDDashboards = $True
    )

    if ($RemoveAllOtherUDDashboards) {
        Get-UDDashboard | Stop-UDDashboard
    }

    Remove-Variable -Name PUDSyncHT -Scope Global -Force -ErrorAction SilentlyContinue
    $global:PUDSyncHT = [hashtable]::Synchronized(@{})
    $global:PUDSyncHT.Add("TestCredObj",$null)

    $MyDashboard = New-UDDashboard -Title "Hello, World" -Content {
        New-UDTextbox -Id "LocalUserName" -Label "Local UserName" -Type text
        New-UDTextbox -Id "LocalPassword" -Label "Local Password" -Type password
        New-UDTextbox -Id "DomainUserName" -Label "Domain UserName" -Type text
        New-UDTextbox -Id "DomainPassword" -Label "Domain Password" -Type password
        New-UDTextbox -Id "SSHPublicCert" -Label "SSH Public Certificate" -Type text
        New-UDSelect -Id "PreferredPSRemotingCredType" -Label "Credential Type" -Option {
            New-UDSelectOption -Name "Domain" -Value "Domain" -Selected
            New-UDSelectOption -Name "Local" -Value "Local"
        }
        New-UDSelect -Id "PreferredPSRemotingMethod" -Label "PSRemoting Method" -Option {
            New-UDSelectOption -Name "WinRM" -Value "WinRM" -Selected
            New-UDSelectOption -Name "SSH" -Value "SSH"
        }

        New-UDButton -Text "Get Input" -OnClick {
            $PUDSyncHT = $global:PUDSyncHT

            $Session:CheckingCredentials = $True
            Sync-UDElement -Id "CheckingCredentials"

            $LocalUserNameTextBox = Get-UDElement -Id "LocalUserName"
            $LocalPasswordTextBox = Get-UDElement -Id "LocalPassword"
            $DomainUserNameTextBox = Get-UDElement -Id "DomainUserName"
            $DomainPasswordTextBox = Get-UDElement -Id "DomainPassword"
            $SSHPublicCertTextBox = Get-UDElement -Id "SSHPublicCert"
            $PrefCredTypeSelection = Get-UDElement -Id "PreferredPSRemotingCredType"
            $PrefRemotingMethodSelection = Get-UDElement -Id "PreferredPSRemotingMethod"
            
            $Local_UserName = $LocalUserNameTextBox.Attributes['value']
            $Local_Password = $LocalPasswordTextBox.Attributes['value']
            $Domain_UserName = $DomainUserNameTextBox.Attributes['value']
            $Domain_Password = $DomainPasswordTextBox.Attributes['value']
            $SSHPublicCertString = $SSHPublicCertTextBox.Attributes['value']
            $Preferred_PSRemotingCredType = $($PrefCredTypeSelection.Content | foreach {
                $_.ToString() | ConvertFrom-Json
            } | Where-Object {$_.attributes.selected.isPresent}).attributes.value
            $Preferred_PSRemotingMethod = $($PrefRemotingMethodSelection.Content | foreach {
                $_.ToString() | ConvertFrom-Json
            } | Where-Object {$_.attributes.selected.isPresent}).attributes.value

            $TestingCredsObj = [pscustomobject]@{
                LocalUserNameTextBox            = $LocalUserNameTextBox
                LocalPasswordTextBox            = $LocalPasswordTextBox
                DomainUserNameTextBox           = $DomainUserNameTextBox
                DomainPasswordTextBox           = $DomainPasswordTextBox
                SSHPublicCertTextBox            = $SSHPublicCertTextBox
                PrefCredTypeSelection           = $PrefCredTypeSelection
                PrefRemotingMethodSelection     = $PrefRemotingMethodSelection
                Local_UserName                  = $Local_UserName
                Local_Password                  = $Local_Password
                Domain_UserName                 = $Domain_UserName
                Domain_Password                 = $Domain_Password
                SSHPublicCertString             = $SSHPublicCertString
                Preferred_PSRemotingCredType    = $Preferred_PSRemotingCredType
                Preferred_PSRemotingMethod      = $Preferred_PSRemotingMethod
            }
            
            $PUDSyncHT.TestCredObj = $TestingCredsObj
        }
    }

    Start-UDDashboard -Dashboard $MyDashboard
}
'@

. "$HOME\Test-UD.ps1"
Import-Module UniversalDashboard.Community
Test-UD

# Navigate to the Dashboard, input some text in one or more fields, and then click the "Get Input" button

$PUDSyncHT.TestCredObj
```

All of the pscustomobject properties are `$null`. This worked in previous versions :(

**Comment by adamdriscoll** [comment] 2018-09-02 06:15
This is a duplicate of #333 and a fix has already been pushed. I'll get a build out in a day or so to resolve this and some other things.

**Closed by adamdriscoll** 2018-09-02 06:15 UTC
