### ISSUE TITLE
Windows Authentication broken in IE

### ISSUE THREAD

**Issue by tholabrk** [ironmansoftware/universal-dashboard#1318] opened 2019-11-13 12:34 UTC
I am having some trouble getting Windows Authentication to work in IE on 2.6.2 (I tested in 2.7.0 as well, but acording to #1309 there seems to be some other issues as well)

It all works fine in both Chrome and (Chr)Edge, but I get a http 500 on IE on the signin-wsfed endpoint, I enabled logging and get the following excerpt when trying to access the homepage:

```
13:23:26 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 164.8637ms 200 text/css
13:23:26 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request starting HTTP/1.1 POST https://<url>/signin-wsfed application/x-www-form-urlencoded 6978
13:23:26 [Warn] Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler '.AspNetCore.Correlation.WsFederation.q9Do7aC835VWoMnszd9MI6osRzII_CznqnOid0LTVg0' cookie not found.
13:23:26 [Info] Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler Error from RemoteAuthentication: Correlation failed..
13:23:26 [Error] Microsoft.AspNetCore.Server.Kestrel Connection id "0HLR86H3S3CLA", Request id "0HLR86H3S3CLA:00000001": An unhandled exception was thrown by the application.
```

For completeness sake, I have included the 2.7 variant as well:
```
13:18:40 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request starting HTTP/1.1 POST https://<url>/signin-wsfed application/x-www-form-urlencoded 6978
13:18:40 [Info] Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action UniversalDashboard.Controllers.DashboardController.Theme (UniversalDashboard) in 134.7695ms
13:18:40 [Info] Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 242.5497ms 200 text/css
13:18:40 [Info] Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler Error from RemoteAuthentication: Unsolicited logins are not allowed..
13:18:40 [Error] Microsoft.AspNetCore.Server.Kestrel Connection id "0HLR86EENA7NM", Request id "0HLR86EENA7NM:00000001": An unhandled exception was thrown by the application.
```

I'm testing it right now so it's basically just the hello world script, but with authentication added:
```
$Authentication = New-UDAuthenticationMethod -MetadataAddress 'https://<fs-url>/FederationMetadata/2007-06/FederationMetadata.xml' -Wtrealm https://<url>
$LoginPage = New-UDLoginPage -AuthenticationMethod $Authentication
$HomePage = New-UDPage -Name "Home" -Endpoint {
    New-UDHeading -Text "Hello, $([System.Net.Dns]::GetHostEntry($Request.HttpContext.Connection.RemoteIpAddress.Tostring()).HostName)!" -Size 1
}
$Dashboard = New-UDDashboard -LoginPage $LoginPage -Title "Hello World" -Pages $HomePage

Start-UDDashboard -Dashboard $Dashboard -Port 443 -Certificate $cert -Design
```

Only other thing is that Chrome/(Chr)Edge is mad because my certificate doesn't have the proper SAN's, but since those are the browsers it actually work on, I don't assume it's an issue.

**Comment by Jacob-Evans** [comment] 2019-11-13 13:42
I would say this is probably not worth fixing that much, even Microsoft recommends against using it as a browser anymore: 

https://www.zdnet.com/article/microsoft-security-chief-ie-is-not-a-browser-so-stop-using-it-as-your-default/

**Comment by tholabrk** [comment] 2019-11-13 13:58
Yeah I know, but unfortunately they have also basically committed to supporting it forever, and for that reason it's a work policy dependency I cannot ignore.

**Comment by psDevUK** [comment] 2019-11-14 09:37
Hi @tholabrk  I have to use IE for work reasons as well, and I have active directory authentication working fine in all versions...I am using this method here:-
 https://github.com/psDevUK/psUniversalDashboard/tree/master/PagesGitHub
This allows me to authenticate users based on a security group.  I hope this helps

**Comment by adamdriscoll** [comment] 2019-11-20 22:06
For what it's worth, I have 2.7.0 (latest nightly) working with Windows auth and with authorization policies. I'll take a look at WSFed and see if I can figure out why it isn't working in IE. 

```
$AuthenticationMethod = New-UDAuthenticationMethod -Windows

$AuthenticationPolicy = New-UDAuthorizationPolicy -Name 'Policy' -Endpoint {
    param($ClaimsPrincipal)

    $ClaimsPrincipal.Identity.Name -eq 'DESKTOP-RB1QJB4\iis'
}

$LoginPage = New-UDLoginPage -AuthenticationMethod $AuthenticationMethod -AuthorizationPolicy $AuthenticationPolicy

$Cache:MyValue = "True"

$Page1 = New-UDPage -Name "CanSee" -Content {}
$Page2 = New-UDPage -Name "CantSee" -Content {} -AuthorizationPolicy "Policy"

$Dashboard = New-UDDashboard -Title 'Test' -Pages @($Page1, $Page2) -LoginPage $LoginPage 
Start-UDDashboard  -Port 10000 -Force  -Dashboard $Dashboard -AllowHttpForLogin -Wait -AdminMode
```

![image](https://user-images.githubusercontent.com/1256531/69282357-54e59f00-0ba7-11ea-989c-71caf53a393b.png)

![image](https://user-images.githubusercontent.com/1256531/69282374-5f079d80-0ba7-11ea-8938-01a909a1327c.png)

**Comment by adamdriscoll** [comment] 2019-11-30 20:43
Marking this a dupe of #1299.

**Closed by adamdriscoll** 2019-11-30 20:43 UTC
Labels: bug, enterprise
