### ISSUE TITLE
Cannot read property 'map' of null

### ISSUE THREAD

**Issue by ehrnst** [ironmansoftware/universal-dashboard#148] opened 2018-05-08 07:48 UTC
Hi,

I upgraded to 1.6 and get this error. Dashboard worked just fine in 1.5. Is there an easy way to get a more detailed error message?

**Comment by adamdriscoll** [comment] 2018-05-08 12:03
Hi,

This is due to a JavaScript error and likely a bug in UD. Can you please open your web browser, open the developer tools (F12) and reproduce the error?

**Comment by ehrnst** [comment] 2018-05-08 12:08
Hi Adam,
Something with react javascript?

`signalr-clientES5-1.0.0-alpha2-final.min.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State
    at e.value (signalr-clientES5-1.0.0-alpha2-final.min.js:1)
    at signalr-clientES5-1.0.0-alpha2-final.min.js:1
    at new Promise (<anonymous>)
    at new t (signalr-clientES5-1.0.0-alpha2-final.min.js:1)
    at e.value (signalr-clientES5-1.0.0-alpha2-final.min.js:1)
    at t.value (ud-dashboard.jsx:111)
    at commitLifeCycles (react-dom.production.min.js:148)
    at t (react-dom.production.min.js:157)
    at y (react-dom.production.min.js:168)
    at v (react-dom.production.min.js:167)`

`

  | l | @ | react-dom.production.min.js:163
-- | -- | -- | --
  | s | @ | react-dom.production.min.js:161
  | y | @ | react-dom.production.min.js:167
  | v | @ | react-dom.production.min.js:167
  | m | @ | react-dom.production.min.js:165
  | f | @ | react-dom.production.min.js:164
  | enqueueSetState | @ | react-dom.production.min.js:107
  | o.setState | @ | react.production.min.js:11
  | (anonymous) | @ | ud-element.jsx:75
  | Promise.then (async) |   |  
  | t.fetchGet | @ | fetch-service.jsx:20
  | value | @ | ud-element.jsx:66
  | value | @ | ud-element.jsx:97
  | mountClassInstance | @ | react-dom.production.min.js:109
  | beginWork | @ | react-dom.production.min.js:133
  | o | @ | react-dom.production.min.js:160
  | i | @ | react-dom.production.min.js:160
  | s | @ | react-dom.production.min.js:161
  | y | @ | react-dom.production.min.js:167
  | v | @ | react-dom.production.min.js:167
  | m | @ | react-dom.production.min.js:165
  | f | @ | react-dom.production.min.js:164
  | enqueueSetState | @ | react-dom.production.min.js:107
  | o.setState | @ | react.production.min.js:11
  | (anonymous) | @ | ud-page.jsx:44
  | Promise.then (async) |   |  
  | t.fetchGet | @ | fetch-service.jsx:20
  | value | @ | ud-page.jsx:36
  | value | @ | ud-page.jsx:31
  | value | @ | ud-page.jsx:24
  | mountClassInstance | @ | react-dom.production.min.js:109
  | beginWork | @ | react-dom.production.min.js:133
  | o | @ | react-dom.production.min.js:160
  | i | @ | react-dom.production.min.js:160
  | s | @ | react-dom.production.min.js:161
  | y | @ | react-dom.production.min.js:167
  | v | @ | react-dom.production.min.js:167
  | m | @ | react-dom.production.min.js:165
  | f | @ | react-dom.production.min.js:164
  | enqueueSetState | @ | react-dom.production.min.js:107
  | o.setState | @ | react.production.min.js:11
  | (anonymous) | @ | ud-dashboard.jsx:173
  | Promise.then (async) |   |  
  | t.fetchGet | @ | fetch-service.jsx:20
  | value | @ | ud-dashboard.jsx:155
  | value | @ | ud-dashboard.jsx:115
  | mountClassInstance | @ | react-dom.production.min.js:109
  | beginWork | @ | react-dom.production.min.js:133
  | o | @ | react-dom.production.min.js:160
  | i | @ | react-dom.production.min.js:160
  | s | @ | react-dom.production.min.js:161
  | y | @ | react-dom.production.min.js:167
  | v | @ | react-dom.production.min.js:167
  | m | @ | react-dom.production.min.js:165
  | f | @ | react-dom.production.min.js:164
  | updateContainer | @ | react-dom.production.min.js:173
  | (anonymous) | @ | react-dom.production.min.js:223
  | unbatchedUpdates | @ | react-dom.production.min.js:170
  | hn | @ | react-dom.production.min.js:223
  | render | @ | react-dom.production.min.js:225
  | (anonymous) | @ | index.jsx:46
  | t | @ | bootstrap f789062…:19
  | (anonymous) | @ | main.f789062357fecb3…eae.bundle.js:44511
  | t | @ | bootstrap f789062…:19
  | (anonymous) | @ | bootstrap f789062…:62
  | (anonymous) | @ | bootstrap f789062…:62

`

**Comment by adamdriscoll** [comment] 2018-05-08 12:14
Hmmm. Is there any way you could provide a sample of the dashboard that is failing?

**Comment by ehrnst** [comment] 2018-05-08 13:10
yep. See if this works. Essentially i have one input to select a customer. After selected a new form will appear with data from the selecte customer

`$1 = New-UDPage -Name test -Content {
            New-UDInput -Title "Select existing customer" -Id "existingCust" -Content {
                New-UDInputField -Type 'select' -Name 'Customer' -Values $cust.Name

            } -Endpoint {
                param($Customer)
                $selctedCustomer = (Invoke-RestMethod -Uri "https://$ApiURL/api/company?name=$customer" -UseDefaultCredentials)
                $custGUID = $selctedCustomer.GUID
                $contact = (Invoke-RestMethod -Uri "https://$ApiURL/api/customercontact?company=$custGUID" -UseDefaultCredentials).companyContacts | where-object {$_.role.Primary -eq $true}

                New-UDInputAction -Toast $contact.name
                $randomDomain = (get-random 9999) + ".onmicrosoft.com"

                # Output a new card based on that info
                New-UDInputAction -Content @(
                    New-UDInput -Title "Creating new tenant for $($customer)" -id "selectedCust" -Content {
                        New-UDInputField -Type textbox -Name 'Company' -Placeholder "Company" -DefaultValue "$($customer)"
                        New-UDInputField -Type textbox -Name 'Domain' -Placeholder 'Domain' -DefaultValue $randomDomain
                        New-UDInputField -Type textbox -Name 'FirstName' -Placeholder 'First name' -DefaultValue "$($contact.User.Person.FirstName)"
                        New-UDInputField -Type textbox -Name 'LastName' -Placeholder 'Last name' -DefaultValue "$($contact.User.Person.LastName)"
                        New-UDInputField -Type textbox -Name 'EMail' -Placeholder 'Email address' -DefaultValue "test@test.no"
                        New-UDInputField -Type textbox -Name 'Phone' -Placeholder 'Phone' -DefaultValue "$($contact.User.Person.Mobile)"
                        New-UDInputField -Type textbox -Name 'Address' -Placeholder 'Address' -DefaultValue "$($contact.user.person.location.address.StreetName) $($contact.user.person.location.address.StreetNumber)"
                        New-UDInputField -Type select -Name 'Country' -Placeholder 'Country' -Values $countries -DefaultValue 'NO'
                        New-UDInputField -Type textbox -Name 'City' -Placeholder 'City' -DefaultValue "$($contact.user.person.location.address.City)"
                        New-UDInputField -Type textbox -Name 'Region' -Placeholder 'Region' -DefaultValue "$($contact.user.person.location.address.City)"
                        New-UDInputField -Type textbox -Name 'Language' -Placeholder 'Language' -DefaultValue "EN"
                        New-UDInputField -Type textbox -Name 'State' -Placeholder 'State' -DefaultValue "Oslo"
                        New-UDInputField -Type textbox -Name 'PostalCode' -Placeholder 'Postal code' -DefaultValue "$($contact.user.person.location.address.ZipCode)"
                        New-UDInputField -Type textbox -Name 'Culture' -Placeholder 'Culture' -DefaultValue "en-us"

                        New-UDInputField -Type switch -Name 'AADP1' -Placeholder 'AAD p1' -Values @("16C9F982-A827-4003-A88E-E75DF1927F27")
                        New-UDInputField -Type switch -Name '365E1' -Placeholder '365 E1' -Values @("91FD106F-4B2C-4938-95AC-F54F74E9A239")
                    } -Endpoint {
                        param($Domain, $Company, $PostalCode, $region, $Firstname, $LastName, $Email, $phone, $Address, $Language, $Culture, $City, $State, $Country, $365E1, $AADP1)


                        #region post
                        $eventID = Get-Random 99999
                        $correlationId = (new-guid)
                        $offersID = @("91FD106F-4B2C-4938-95AC-F54F74E9A239")
                        $quantity = (get-random -Minimum 1 -Maximum 8)
                        $friendlyName = "event grid test"

                        #Date format should be SortableDateTimePattern (ISO 8601)
                        $eventDate = Get-Date -Format s

                        #Construct body using Hashtable
                        $htbody = @{
                            id          = $eventID
                            eventType   = "test"
                            subject     = "Tenant-Registered"
                            eventTime   = $eventDate   
                            data        = @{
                                "correlationId" = $correlationId
                                "cspDomain"     = "cspdomain.onmicrosoft.com"
                                "sandbox"       = $true
                                "CompanyName"   = $Company
                                "domain"        = $domain
                                "Country"       = $Country
                                "City"          = $City
                                "State"         = $State
                                "Region"        = $region
                                "Culture"       = $Culture
                                "Language"      = $Language
                                "PostalCode"    = $PostalCode
                                "FirstName"     = $Firstname
                                "Email"         = $Email
                                "LastName"      = $LastName
                                "Address"       = $Address
                                "Phone"         = $phone
                                "order"         = @(
                                    @{
                                        "offerID"      = $AADP1
                                        "quantity"     = $quantity
                                        "friendlyName" = $friendlyName
                                    },
                                    @{
                                        "offerID"      = $365E1
                                        "quantity"     = $quantity
                                        "friendlyName" = $friendlyName
                                    }
                                )
                            }
                            dataVersion = "1.0"
                        }
                        $body = "[" + (ConvertTo-Json $htbody -Depth 4) + "]"

                        $createTenant = Invoke-RestMethod -Uri "https://*eventgrid.azure.net/api/events" -Method POST -Body $body -Headers @{"aeg-sas-key" = "555"}
                        #endregion

                        New-UDInputAction -Toast "setting up tenant..." -Duration 10 -ClearInput
                    }
                )
            }
        }


$Dash = New-UDDashboard -Footer $footer -Title "test" -NavBarColor "#406997" -Page @(
    $1
)


Start-UDDashboard -Port 1200 -Dashboard $Dash -AllowHttpForLogin`

**Comment by adamdriscoll** [comment] 2018-05-08 16:54
@ehrnst It looks like this is happening when the `-Values` parameter is null. For example, if $cust.name is null, it will show this error in the UI. 

Is it possible those values are null in your dashboard? 

I will fix it in the UI so it doesn't do this but will still show an empty select if they are null.

**Comment by ehrnst** [comment] 2018-05-09 07:25
Hmm.... it's not empty and it worked fine in 1.5
Anyway, changed from `$cust.Name` to `$($cust.name)` everything works fine now.

Thank you, and keep up the good work!

**Comment by adamdriscoll** [comment] 2018-05-10 00:25
I've fixed the JavaScript side of this. Not sure what changed in the PowerShell side to cause an issue but you won't run into this issue again when the `-ValidOptions` parameter is null. Fixed in 1.6.2

**Closed by adamdriscoll** 2018-05-10 00:25 UTC
Labels: bug
