### ISSUE TITLE
dynamic page with cycle pages

### ISSUE THREAD

**Issue by dotraphael** [ironmansoftware/universal-dashboard#277] opened 2018-07-23 14:51 UTC
created a dynamic page that uses cached data to be shared between pages, however, when using dynamic pages the cycle option will not work. would be great to be able to use the dynamic pages functionality with cycle.

**Comment by adamdriscoll** [comment] 2018-07-24 01:09
Duplicate of #244

**Closed** 2018-08-03 12:15 UTC
Labels: bug, duplicate
