### ISSUE TITLE
Enhancement for new ud input layout

### ISSUE THREAD

**Issue by psDevUK** [ironmansoftware/universal-dashboard#867] opened 2019-06-08 14:27 UTC
This is a request only if possible, but I have noticed on forms where I have a lot of user input / interaction sometimes the formatting looks wonky, like only one input field looks out of place, but it could have gone on the same line as the other inputs.  Happy to email you some screen shots if you cannot replicate your end....like put 12 input objects, then resize the page a bit, or even without resizing.  I can tweak it with the grid layout but then on a different higher resolution screen looks wonky again

**Comment by adamdriscoll** [comment] 2019-08-07 17:44
Duplicate of #744

**Closed by adamdriscoll** 2019-08-07 17:44 UTC
Labels: enhancement
