### ISSUE TITLE
UDLoggin not working in ISE

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#299] opened 2018-08-08 21:09 UTC
UDLogging doesn't seem to work in ISE anymore, but works in VSCode

**Comment by mkellerman** [comment] 2018-08-08 21:43
Works when using powershell.exe directly

**Comment by adamdriscoll** [comment] 2018-08-09 15:37
Duplicate of #95 ;)

**Closed by adamdriscoll** 2018-08-09 15:37 UTC
