### ISSUE TITLE
Sync-UDElement -Wait

### ISSUE THREAD

**Issue by mkellerman** [ironmansoftware/universal-dashboard#745] opened 2019-04-11 22:53 UTC
Add the option to -Wait for element to be completed to be loaded.

This would allow for update elements to only occur once we are 100% some other elements are loaded.

**Comment by adamdriscoll** [comment] 2019-12-18 00:18
Duplicate of #1382. This is non-trivial and why it hasn't been implemented. The problem is that SignalR websockets are fire and forget and do not have callbacks. Sync-UDElement uses SignalR websockets so we need to do bit of work to get that guts working for the control. 

Additionally, we need to enhance the JS API because currently we would have to update every control to support this functionality.

**Closed by adamdriscoll** 2019-12-18 00:18 UTC
Labels: enhancement
