### ISSUE TITLE
1.6 Beta-2 : New-UDButton still missing

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#94] opened 2018-04-23 20:04 UTC
I had to add it to the manifest in order to make it work.

**Comment by adamdriscoll** [comment] 2018-04-23 20:06
This is a duplicate of: https://github.com/ironmansoftware/universal-dashboard/issues/89

The manifest has been corrected for beta3

**Closed by adamdriscoll** 2018-04-23 20:06 UTC
Labels: bug, duplicate
