### ISSUE TITLE
New-UDSwitch - broken in beta3

### ISSUE THREAD

**Issue by Phyziik** [ironmansoftware/universal-dashboard#112] opened 2018-04-26 18:26 UTC
> Cannot read property 'type' of undefined

This is the error that I get when I try to display a switch.

1.6.0  - Beta3

**Comment by adamdriscoll** [comment] 2018-04-26 20:42
Duplicate of #111 

I pushed a beta4 since this involved so many components.

**Closed by adamdriscoll** 2018-04-26 20:42 UTC
