### ISSUE TITLE
Every UDButton with OnClick Event throws exception 

### ISSUE THREAD

**Issue by e1ze** [ironmansoftware/universal-dashboard#939] opened 2019-07-03 16:06 UTC
Hi, 

after upgrading to 2.5.0 and 2.5.1 from 2.4.1 everytime i use an OnClick Event with New-UDButton i get the following error: 

> An unexpected error occurred invoking 'clientEvent' on the server. RuntimeBinderException: object enthält keine Definition für Error.
![grafik](https://user-images.githubusercontent.com/6794362/60607050-c66dae00-9dbc-11e9-8a8b-7a105a37dd3e.png)
(Translated german text: object does not contain a definition for Error)

I did not get any errors in 2.4.1.
I get the errors locally and when hosting UD in IIS. 
It doesn't matter what I call with the OnClick event. The error message appears every time I press the button. No errors in the browser (Developer Tools) or with UDDebugging.

Example Code (Used in UDGrid when clicking on the Username an UDModal with the Description is displayed):

```powershell
New-UDButton -Flat -Text $_.Name -OnClick { 
  Show-UDModal -Header {
    New-UDHeading -Size 5 -Text "Description for User '$($_.SamAccountName)'" 
  } -Content {
    New-UDRow -Columns 
    { New-UDColumn -Size 8 -Content 
      {
        if ($_.Description) 
        {
          $_.Description 
        }
        else 
        {
          "No Description" 
        } 
      }
      New-UDColumn -Size 8 -Content {
        New-UDButton -BackgroundColor $Cache:LoginBGColor -Text "Close" -OnClick { Hide-UDModal } 
      } 
    } 
  } 
}
```

I get the error in the above example when clicking on the first flat button and also when clicking on the "Close" Button inside the modal. As already said, but I get the error message with every button.

Any Ideas?

Thanks

**Comment by adamdriscoll** [comment] 2019-07-03 16:25
Duplicate of #935 - Fixed in 2.5.2

**Closed by adamdriscoll** 2019-07-03 16:25 UTC
