### ISSUE TITLE
UD-Grid Sorting is Case Sensitive

### ISSUE THREAD

**Issue by awickham10** [ironmansoftware/universal-dashboard#1048] opened 2019-08-26 18:21 UTC
#### Describe the Issue
When sorting mixed case values in a column it appears that it is sorting uppercase alphabetical first and then lowercase alphabetical.

#### To Reproduce
1. Start dashboard with a grid.
2. Click the header to sort.

#### Expected behavior
Case should be ignored when sorting, or at least have the option to ignore case when sorting.

#### Screenshots
![image](https://user-images.githubusercontent.com/7840633/63712889-9830ab80-c80c-11e9-92b1-7dc69478ec48.png)

#### Script Sample
```powershell
Start-UDDashboard -Port 8080 -Force -Content {
    New-UDDashboard -Title 'Test' -Content {
        New-UDGrid -Title 'Data' -Endpoint {
            @(
                @{Header = 'A'},
                @{Header = 'B'},
                @{Header = 'C'},
                @{Header = 'a'},
                @{Header = 'b'},
                @{Header = 'c'}
            )    | Out-UDGridData
        }
    }
}
```

#### Version Information
- **Operating System**: Windows 10
- **PowerShell Version**: 5.1
- **Universal Dashboard Version**: 2.5.3
- **UD Hosting Method**: PowerShell

**Comment by adamdriscoll** [comment] 2020-02-04 21:02
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.universaldashboard.io/t/case-sensitive-udgrid-sorting/2152/1

**Comment by adamdriscoll** [comment] 2020-02-04 22:34
Duplicate of #471 - We will use that to track. Targeting a fix for 2.9.

**Closed by adamdriscoll** 2020-02-04 22:34 UTC
Labels: bug

**Comment by awickham10** [comment] 2020-02-04 23:18
Is this actually a duplicate? My issue was for the sort order of data and the other issue is for case sensitivity with property names isn't it?
