### ISSUE TITLE
Need the ability to send toasts at anytime with any control

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#76] opened 2018-04-15 17:02 UTC
I'd like to be able to send a toast to a user when he press a button (or something else) and not only in a form with New-UDInputAction.

Thanks Adam! :-)

**Comment by adamdriscoll** [comment] 2018-04-16 01:15
Hey Arnaud, 

This is a duplicate of #54. It's on my radar and I will try and get into 1.6.0.

**Closed by adamdriscoll** 2018-04-16 01:15 UTC

**Comment by adamdriscoll** [comment] 2018-04-16 01:34
This is implemented in 1.6.0. Had it mostly implemented but just fixed a bug that was preventing it from working.

**Comment by apetitjean** [comment] 2018-04-16 07:40
Very cool! Thanks!
