### ISSUE TITLE
2.3.1 - UDtheme not being applied to New-UDCard

### ISSUE THREAD

**Issue by kdf2883** [ironmansoftware/universal-dashboard#651] opened 2019-02-19 23:34 UTC
Using this code:

```
Start-UDDashboard -Dashboard (

    New-UDDashboard -Content {
        New-UDCard -Content { New-UDHtml "Universal Dashboard Version $((Get-InstalledModule -Name UniversalDashboard.Community).Version)"}
        New-UDCard -Content {"Using UDTheme Azure"}
    } -Theme (Get-UDTheme Azure) 

) -Port 1000

```
In Version 2.2.1 It works as expected:

![image](https://user-images.githubusercontent.com/21251604/53054963-28fc8800-3474-11e9-9e4e-da80944dd9f6.png)

If the same code is ran on 2.3.1 the Card color doesn't change:

![image](https://user-images.githubusercontent.com/21251604/53055218-e4bdb780-3474-11e9-8c5b-83d71878d29a.png)

**Comment by adamdriscoll** [comment] 2019-02-21 12:58
This is a duplicate of #529 and is resolved for the 2.3.2 milestone.

**Closed by adamdriscoll** 2019-02-21 12:58 UTC
